
spring:
  profiles: cloud
  main:
    allow-bean-definition-overriding: true



management:
  cloudfoundry:
    enabled: true
    skip-ssl-validation: true
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
