spring:
  datasource:
    hikari:
      connection-timeout: 60000
      maximum-pool-size: 5
  profiles: cloud
  application:
    name: rahul-cloud-native-spring

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
  cloudfoundry:
    enabled: true
    skip-ssl-validation: true

info: # add this section
  build:
    artifact: @project.artifactId@
    name: @project.name@
    description: @project.description@
    version: @project.version@

endpoint:
  health:
    show-details: always

greeting: hellno


