spring.cloud.stream:
      default:
        consumer:
          useNativeEncoding: true
      bindings:
        input:
          group: ${application.group}
          contentType: application/*+avro
      kafka:
        binder:
          consumer-properties:
            value.deserializer: io.confluent.kafka.serializers.KafkaAvroDeserializer
            schema.registry.url: ${application.schema-registry-url}
            specific.avro.reader: false

spring:
  cloud:
    gcp:
      credentials:
        encoded-key: ewogICJ0eXBlIjogInNlcnZpY2VfYWNjb3VudCIsCiAgInByb2plY3RfaWQiOiAiY2xneC1hb3RmLWFwcC1zYngtM2VjMSIsCiAgInByaXZhdGVfa2V5X2lkIjogIjY3MjllNmJhN2E1ZWM5Yzg5MGEwNTk5Zjk3NDJmOTgzZmIxOTFjNzUiLAogICJwcml2YXRlX2tleSI6ICItLS0tLUJFR0lOIFBSSVZBVEUgS0VZLS0tLS1cbk1JSUV2UUlCQURBTkJna3Foa2lHOXcwQkFRRUZBQVNDQktjd2dnU2pBZ0VBQW9JQkFRRFQzbFkwM2tkUFJXa2RcbmYvVkhEeEdOK0VrZkYzajBlWFNSZHd6a1h0bVg3K2pXMCtuSzdiSlZRRWxJY1d3MlhMdVZpVlBsYWRKQ1g0OTRcbmN2UTUvMGRXRTR3c0FCUTgranYzWEJnd0wvdVlBTDRRRzZUOTA2VHZsU3pIVEJNamtqZmQvaThxSDVmQmZBV0Zcbmk0WkFtYkYxVytyMnBiVWV1VEdsR2ZtNXA3NjRBRzl4c29ic1BBeTRyeVFNWWRSTEhUVzZjdTduQ09wUUladkdcbmhudlIvSmVYd3VkNEZwRitnMjk5SmpBL2tJcU1xMldCR3A5S0crQTV4N3ZabjYxVm1uUkxJdExXVmpBSExVQlhcbkcvamZWSThRRVlDOElvejFEOG9Wa3RHWVpQb2Z4ZHduaFpydzU1dXJ1UFJJcFZOcTRRaC9EZzJOVi9peEwwU0dcbmMrWVV4UTF2QWdNQkFBRUNnZ0VBUU92V1dxanFEUDVsOFdZdVVMSHJYU2VCc0lkT3h3c1lqeUo5enRUSnRHY05cbllCYmJneFZIR2h4eTJFSDVPTWM5cTlyQzNIK0tzRS83OUpxMC83aWJzV0tZQnp1VytBQnRzNlNDdlBGWEZRTFZcbk9yWmQzbkdtRHN3VlJwU25JTFZEYlVEZ1R2WVRXSFNhZEl1R2ZmRWFrYTJ5MkJWNjVJazNEekpnZFdWVGFhb1pcbkhtZ2JqUDZjYkxlVGxRYXRqYjhYNzBsT04rendPM2NPRkVuOWJsSTE2SGcyRlJuNUNMZTdQMHBXdk5ZM3BPUFlcbmZFMUVpbzhPUUh2T3labThsRmZ0SVhYRExnVE8vcE9sVW53a3FJYUZIUzdIbHNVSUJsckhqdi9DT3ZsU3JOYndcbnQvZytBOVY3ZmdqL0lOWXYyVllqZTA0czR4UklhNFk2Y24vU21yWnIwUUtCZ1FELytkTUkvMCs5K2g3dk8xL25cbkNJY1F1Y1cxTGxlYytQencyY0xMKzNkbjdwTGJoZk5mQVF5UVpkRmI0dzZNakJrU1ZVTjJaMlMxR1JHUUROSjBcbnF1NDB6d29ETDlrVWc5SDEwbko5K0VESWNEcTdkenZLT09lUDl0NEd5d1ZQRWNwb044bjFXUkFvaDh2VHhpckdcbnBPQ21LZWhVZ1lQenNreFF3UmpwUVFnSTB3S0JnUURUNDNMQkY0eW43NlJla2dGQnE1R1BOa0NZZVBCdFIvVC9cbk9LTldNU0sreUtYSEYySzY3dHZCNlVxMUhVclc0TWtGUjl6MlFQbzJFanE3T0RVV2JOMkpsUmk1KzJPRnlUdEZcbkl4SjdPYjU0L3BUYTNwc045RmJCNHRuLytmaVJxTGdaZDRqOHorbWNjdnRERy9IVm5yMFhWUCt1WDRQUk1Qb1RcbnRSeUNkNi9IZFFLQmdFNzd5VEJYaDBWNWJoNG5WZm8xMldkQnkwMlNsUm9zZ2UvWFlaSUxiOWF6K01DZjNtNk1cbkpsSlArSCsvMmZkb0t6eEs3dHdVSHpENklUOHZsYWpHTFdaQ0ZEYlRoc29idXFkOVhqS2NiWERyb0ZQRUFNRHZcbk9oUmorakppWnFyMU5GMWdDWU1aRGpGVFpZTmMvRW43Q2c1N2srS3ZiQVhBR0dnNmpQTThTN3hkQW9HQUN1bzhcbmp4WFhlUTh2T0cvdEFLVUY2b3F3NlNuUnVNOXNIM21iY0dVM2xQeGhEZEIybFlxWVozVE5GR2RkNDVQUXh5VGNcbmpSTHIwTDAvcVVWTDlzdkUzY0dBZEpRdW5FV3hkKzVHbFhKMERXZVA0M1owSmxQZjVEejdYZVJTbWE1SFRZaUtcbjFmc2YzWjlPc2paT1R1TE9ldFUyRnBWMUJPR3hBRExrTlJSVlNjRUNnWUVBbW5HQlR0WFlzRnd3aFNmY0J1eWlcbndTbzNmUDhsUCt6Q3JuOVFQWk9ZY0l6V2Vsd2F4VGdmaFJMSEdKVkxFWEU0REpPZnJTa29mWXdLOGg5ejNDUXVcbjJuNi9wU3NGUGZiOEh4ZFBNbmlJYS9CcFdjWms3Z0tJNFozWTNZZjdSZ0Q0MFc0eWdyWXhhL3U3VnJLVlU4WGJcbllWZm1Hb0lWUUl0MUd3T1ZUaDgzU2I4PVxuLS0tLS1FTkQgUFJJVkFURSBLRVktLS0tLVxuIiwKICAiY2xpZW50X2VtYWlsIjogInRmLWNsZ3gtYW90Zi1hcHAtc2J4QGNsZ3gtYW90Zi1hcHAtc2J4LTNlYzEuaWFtLmdzZXJ2aWNlYWNjb3VudC5jb20iLAogICJjbGllbnRfaWQiOiAiMTA3NDQwNDA0NTAyMjIwNjk5Njg3IiwKICAiYXV0aF91cmkiOiAiaHR0cHM6Ly9hY2NvdW50cy5nb29nbGUuY29tL28vb2F1dGgyL2F1dGgiLAogICJ0b2tlbl91cmkiOiAiaHR0cHM6Ly9vYXV0aDIuZ29vZ2xlYXBpcy5jb20vdG9rZW4iLAogICJhdXRoX3Byb3ZpZGVyX3g1MDlfY2VydF91cmwiOiAiaHR0cHM6Ly93d3cuZ29vZ2xlYXBpcy5jb20vb2F1dGgyL3YxL2NlcnRzIiwKICAiY2xpZW50X3g1MDlfY2VydF91cmwiOiAiaHR0cHM6Ly93d3cuZ29vZ2xlYXBpcy5jb20vcm9ib3QvdjEvbWV0YWRhdGEveDUwOS90Zi1jbGd4LWFvdGYtYXBwLXNieCU0MGNsZ3gtYW90Zi1hcHAtc2J4LTNlYzEuaWFtLmdzZXJ2aWNlYWNjb3VudC5jb20iCn0=


application:
  bucketName: aotf-listing-events
  group: unitType-group-gcs
  schemaRegistryUrl: http://localhost:8081
  schemaRegistryCacheCapacity: 10
  deadLetterTopic: unitType-dead-gcs
  maxRetries: 2


message:
  messageKey: UnitTypeKey,OriginatingSystemName
  parentKey: ListingKey,OriginatingSystemName
  blobFileKeys: UnitTypeKey,OriginatingSystemName,Nucleus_PostDate
  delimiter: '~'
  filePrefix: UnitType

server:
  port: 0
